version: '3.8'
services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_DB=scrapper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data:/Users/ajaysankaran/Desktop/code/db/
volumes:
  db:
    driver: local